### Task 2


In [1]:
import numpy as np
import scipy.linalg
a = np.array([2, 4, 6])
b = np.array([8, 10, 12])
c = np.array([1, 3, 5])
d = np.array([7, 9, 11])
print(a)
print(b)
print(c)
print(d)

[2 4 6]
[ 8 10 12]
[1 3 5]
[ 7  9 11]


In [2]:
a.ndim

1

In [3]:
a.size

3

In [4]:
a.shape

(3,)

In [5]:
a.shape[1-1]

3

In [6]:
np.array([[1. ,2. ,3.], [4. ,5. ,6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
a = np.vstack([np.hstack([c,d]), np.hstack([a,b]), np.hstack([13, 15, 17, 19, 21, 23]), 
            np.hstack([14, 16, 18, 20, 22, 24]), np.hstack([25, 27, 29, 31, 33, 35]),
            np.hstack([26, 28, 30, 32, 34, 36])])

In [8]:
a[[-1]]

array([[26, 28, 30, 32, 34, 36]])

In [9]:
print(a)
a[1,4]

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [13 15 17 19 21 23]
 [14 16 18 20 22 24]
 [25 27 29 31 33 35]
 [26 28 30 32 34 36]]


10

In [10]:
a[1,:]

array([ 2,  4,  6,  8, 10, 12])

In [11]:
print(a)
a[0:5,:]

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [13 15 17 19 21 23]
 [14 16 18 20 22 24]
 [25 27 29 31 33 35]
 [26 28 30 32 34 36]]


array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [13, 15, 17, 19, 21, 23],
       [14, 16, 18, 20, 22, 24],
       [25, 27, 29, 31, 33, 35]])

In [12]:
a[-5:]

array([[ 2,  4,  6,  8, 10, 12],
       [13, 15, 17, 19, 21, 23],
       [14, 16, 18, 20, 22, 24],
       [25, 27, 29, 31, 33, 35],
       [26, 28, 30, 32, 34, 36]])

In [13]:
a[0:3][:,3:5]

array([[ 7,  9],
       [ 8, 10],
       [19, 21]])

In [14]:
a[np.ix_([1,3,4],[0,2])]

array([[ 2,  6],
       [14, 18],
       [25, 29]])

In [15]:
a[ 2:21:2,:]

array([[13, 15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33, 35]])

In [16]:
a[ ::2,:]

array([[ 1,  3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33, 35]])

In [17]:
a[ ::-1,:]

array([[26, 28, 30, 32, 34, 36],
       [25, 27, 29, 31, 33, 35],
       [14, 16, 18, 20, 22, 24],
       [13, 15, 17, 19, 21, 23],
       [ 2,  4,  6,  8, 10, 12],
       [ 1,  3,  5,  7,  9, 11]])

In [18]:
a[np.r_[:len(a),0]]

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [13, 15, 17, 19, 21, 23],
       [14, 16, 18, 20, 22, 24],
       [25, 27, 29, 31, 33, 35],
       [26, 28, 30, 32, 34, 36],
       [ 1,  3,  5,  7,  9, 11]])

In [19]:
print(a)
a.T

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [13 15 17 19 21 23]
 [14 16 18 20 22 24]
 [25 27 29 31 33 35]
 [26 28 30 32 34 36]]


array([[ 1,  2, 13, 14, 25, 26],
       [ 3,  4, 15, 16, 27, 28],
       [ 5,  6, 17, 18, 29, 30],
       [ 7,  8, 19, 20, 31, 32],
       [ 9, 10, 21, 22, 33, 34],
       [11, 12, 23, 24, 35, 36]])

In [20]:
a.conj().T

array([[ 1,  2, 13, 14, 25, 26],
       [ 3,  4, 15, 16, 27, 28],
       [ 5,  6, 17, 18, 29, 30],
       [ 7,  8, 19, 20, 31, 32],
       [ 9, 10, 21, 22, 33, 34],
       [11, 12, 23, 24, 35, 36]])

In [21]:
a = np.random.rand(3,2)
b = np.random.rand(2,4)
print(a)
print(b)
a.dot(b)

[[0.49276135 0.13231604]
 [0.53900955 0.35288319]
 [0.2489034  0.22776163]]
[[0.26433004 0.99942769 0.14925356 0.69637502]
 [0.82705719 0.92311051 0.74680825 0.33670562]]


array([[0.23968456, 0.61462166, 0.1723611 , 0.38769825],
       [0.43433099, 0.86445125, 0.34398517, 0.49417054],
       [0.25416454, 0.45901011, 0.20724398, 0.25001873]])

In [22]:
b = np.random.rand(3,2)
print(b)
a*b

[[0.89734124 0.44841452]
 [0.4918996  0.03417347]
 [0.58988991 0.19815717]]


array([[0.44217508, 0.05933243],
       [0.26513858, 0.01205924],
       [0.14682561, 0.0451326 ]])

In [23]:
a/b

array([[ 0.54913485,  0.29507528],
       [ 1.09577147, 10.32623332],
       [ 0.42194891,  1.14939889]])

In [24]:
a**3

array([[0.11964923, 0.00231653],
       [0.15659914, 0.04394332],
       [0.01542029, 0.01181522]])

In [25]:
(a>0.5)

array([[False, False],
       [ True, False],
       [False, False]])

In [26]:
np.nonzero(a>.5)

(array([1]), array([0]))

In [27]:
v = np.random.rand(1,2)
print(a)
print(v)
a[:,np.nonzero(v>0.5)[0]]

[[0.49276135 0.13231604]
 [0.53900955 0.35288319]
 [0.2489034  0.22776163]]
[[0.63913305 0.15746713]]


array([[0.49276135],
       [0.53900955],
       [0.2489034 ]])

In [28]:
v = np.random.rand(2,1)

print(v.T)
#a[:,v.T>0.5]

[[0.95300622 0.88466532]]


In [29]:
a[a<0.5]=0
print(a)

[[0.         0.        ]
 [0.53900955 0.        ]
 [0.         0.        ]]


In [30]:
a[:] = 3
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]]


In [31]:
y = a.copy()
print(y)

[[3. 3.]
 [3. 3.]
 [3. 3.]]


In [32]:
y = a[1,:].copy()
print(y)

[3. 3.]


In [33]:
y = a.flatten()
print(y)

[3. 3. 3. 3. 3. 3.]


In [34]:
np.arange(1.,11.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
np.arange(1.,11.)[:, np.newaxis]


array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [37]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [39]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
a = np.random.rand(4,4)
np.diag(a)

array([0.17751489, 0.5942044 , 0.81607359, 0.00957537])

In [42]:
np.random.rand(3,4)

array([[0.298404  , 0.00405434, 0.97010522, 0.0582224 ],
       [0.37367661, 0.59717098, 0.00441781, 0.87965886],
       [0.3327037 , 0.27579464, 0.50576818, 0.79869409]])

In [43]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [44]:
np.mgrid[0:9.,0:6.] 

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [45]:
np.ogrid[0:9.,0:6.]

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]),
 array([[0., 1., 2., 3., 4., 5.]])]

In [46]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]),
 array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [47]:
np.ix_([1,2,4],[2,4,5])

(array([[1],
        [2],
        [4]]),
 array([[2, 4, 5]]))

In [48]:
np.tile(a, (2, 3))

array([[0.17751489, 0.68411256, 0.20256011, 0.11153342, 0.17751489,
        0.68411256, 0.20256011, 0.11153342, 0.17751489, 0.68411256,
        0.20256011, 0.11153342],
       [0.69634658, 0.5942044 , 0.33460903, 0.92366986, 0.69634658,
        0.5942044 , 0.33460903, 0.92366986, 0.69634658, 0.5942044 ,
        0.33460903, 0.92366986],
       [0.1512082 , 0.04254066, 0.81607359, 0.45762247, 0.1512082 ,
        0.04254066, 0.81607359, 0.45762247, 0.1512082 , 0.04254066,
        0.81607359, 0.45762247],
       [0.82946179, 0.1349125 , 0.86108135, 0.00957537, 0.82946179,
        0.1349125 , 0.86108135, 0.00957537, 0.82946179, 0.1349125 ,
        0.86108135, 0.00957537],
       [0.17751489, 0.68411256, 0.20256011, 0.11153342, 0.17751489,
        0.68411256, 0.20256011, 0.11153342, 0.17751489, 0.68411256,
        0.20256011, 0.11153342],
       [0.69634658, 0.5942044 , 0.33460903, 0.92366986, 0.69634658,
        0.5942044 , 0.33460903, 0.92366986, 0.69634658, 0.5942044 ,
        0.33460903,

In [49]:
a = np.random.rand(1,3)
b = np.random.rand(1,3)
np.hstack((a,b))

array([[0.56278953, 0.36541972, 0.53319426, 0.92904612, 0.57273921,
        0.69098301]])

In [50]:
np.concatenate((a,b))

array([[0.56278953, 0.36541972, 0.53319426],
       [0.92904612, 0.57273921, 0.69098301]])

In [51]:
a.max()

0.5627895302249861

In [52]:
a.max(0)

array([0.56278953, 0.36541972, 0.53319426])

In [53]:
a.max(1)

array([0.56278953])

In [54]:
np.maximum(a,b)

array([[0.92904612, 0.57273921, 0.69098301]])

In [55]:
v = np.random.rand(3,3)
np.sqrt(np.dot(v,v))

array([[0.72476937, 0.89787022, 0.83029377],
       [0.62167338, 0.96982418, 0.81111481],
       [0.55234345, 0.693817  , 0.7471576 ]])

In [56]:
np.logical_and(a,b)

array([[ True,  True,  True]])

In [57]:
np.logical_or(a,b)

array([[ True,  True,  True]])

In [60]:
a = 1
b = 2
a & b

0

In [61]:
a = 1
b = 2
a | b

3

In [62]:
a = np.random.rand(3,3)
print(a)
np.linalg.inv(a)

[[0.32506614 0.84754624 0.8252302 ]
 [0.41797144 0.85604905 0.37829632]
 [0.05124385 0.96716723 0.19207902]]


array([[-1.11728788,  3.52379694, -2.13984699],
       [-0.33776075,  0.11176061,  1.23101285],
       [ 1.9987881 , -1.50284049, -0.42139576]])

In [63]:
np.linalg.pinv(a)

array([[-1.11728788,  3.52379694, -2.13984699],
       [-0.33776075,  0.11176061,  1.23101285],
       [ 1.9987881 , -1.50284049, -0.42139576]])

In [64]:
np.linalg.matrix_rank(a)

3

In [65]:
b = np.random.rand(3,3)
np.linalg.solve(a,b)

array([[-1.53338754e-01,  1.97936865e+00, -3.27305509e-01],
       [ 6.18136895e-01,  4.62795967e-01,  1.93287536e-04],
       [-3.29559132e-01, -6.92157103e-01,  7.20996946e-01]])

In [66]:
U, S, Vh = np.linalg.svd(a)
V = Vh.T
print(V)
print(U)
print(S)

[[-0.26120317  0.31156816 -0.91361818]
 [-0.84311803 -0.53450779  0.05876579]
 [-0.47002649  0.78563777  0.40230386]]
[[-0.6564018   0.64501479  0.39127048]
 [-0.55764895 -0.06553491 -0.82748585]
 [-0.50809874 -0.76135477  0.40270906]]
[1.8089071  0.45982234 0.21676484]


In [67]:
#np.linalg.cholesky(a).T

D,V = np.linalg.eig(a)
print(D)
print(V)

[ 1.60372055+0.j         -0.11526316+0.31486557j -0.11526316-0.31486557j]
[[ 0.67528598+0.j          0.74180144+0.j          0.74180144-0.j        ]
 [ 0.59678907+0.j         -0.13609967-0.2572533j  -0.13609967+0.2572533j ]
 [ 0.4333955 +0.j         -0.25603298+0.54724342j -0.25603298-0.54724342j]]


In [68]:
Q,R = scipy.linalg.qr(a)
#L,U = scipy.linalg.lu(a)
print(Q)
print(R)

[[-0.61105892  0.07347252 -0.788168  ]
 [-0.78570217 -0.17745997  0.59260448]
 [-0.09632813  0.98138155  0.16616601]]
[[-0.53197185 -1.28366569 -0.81999513]
 [ 0.          0.85951699  0.18200209]
 [ 0.          0.         -0.39432294]]


In [69]:
np.fft.fft(a)

array([[ 1.99784259+0.j        , -0.51132208-0.01932626j,
        -0.51132208+0.01932626j],
       [ 1.65231681+0.j        , -0.19920125-0.413746j  ,
        -0.19920125+0.413746j  ],
       [ 1.21049011+0.j        , -0.52837927-0.67124608j,
        -0.52837927+0.67124608j]])

In [70]:
np.fft.ifft(a)

array([[ 0.66594753+0.j        , -0.17044069+0.00644209j,
        -0.17044069-0.00644209j],
       [ 0.55077227+0.j        , -0.06640042+0.13791533j,
        -0.06640042-0.13791533j],
       [ 0.4034967 +0.j        , -0.17612642+0.22374869j,
        -0.17612642-0.22374869j]])

In [71]:
a = np.random.randint(100, size=10)
print(a)
print(np.sort(a))

[85 97 79 27 77 52 32 12 32 89]
[12 27 32 32 52 77 79 85 89 97]


In [72]:
a.squeeze()

array([85, 97, 79, 27, 77, 52, 32, 12, 32, 89])