### Task 2

In [18]:
import numpy as np
import scipy.linalg
a = np.array([2, 4, 6])
b = np.array([8, 10, 12])
c = np.array([1, 3, 5])
d = np.array([7, 9, 11])
print(a)
print(b)
print(c)
print(d)

[2 4 6]
[ 8 10 12]
[1 3 5]
[ 7  9 11]


In [2]:
a.ndim

1

In [3]:
a.size

3

In [4]:
a.shape

(3,)

In [6]:
a.shape[1-1]

3

In [15]:
np.array([[1. ,2. ,3.], [4. ,5. ,6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
a = np.vstack([np.hstack([c,d]), np.hstack([a,b]), np.hstack([13, 15, 17, 19, 21, 23]), 
            np.hstack([14, 16, 18, 20, 22, 24]), np.hstack([25, 27, 29, 31, 33, 35]),
            np.hstack([26, 28, 30, 32, 34, 36])])

In [20]:
a[[-1]]

array([[26, 28, 30, 32, 34, 36]])

In [21]:
print(a)
a[1,4]

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [13 15 17 19 21 23]
 [14 16 18 20 22 24]
 [25 27 29 31 33 35]
 [26 28 30 32 34 36]]


10

In [22]:
a[1,:]

array([ 2,  4,  6,  8, 10, 12])

In [23]:
print(a)
a[0:5,:]

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [13 15 17 19 21 23]
 [14 16 18 20 22 24]
 [25 27 29 31 33 35]
 [26 28 30 32 34 36]]


array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [13, 15, 17, 19, 21, 23],
       [14, 16, 18, 20, 22, 24],
       [25, 27, 29, 31, 33, 35]])

In [24]:
a[-5:]

array([[ 2,  4,  6,  8, 10, 12],
       [13, 15, 17, 19, 21, 23],
       [14, 16, 18, 20, 22, 24],
       [25, 27, 29, 31, 33, 35],
       [26, 28, 30, 32, 34, 36]])

In [25]:
a[0:3][:,3:5]

array([[ 7,  9],
       [ 8, 10],
       [19, 21]])

In [26]:
a[np.ix_([1,3,4],[0,2])]

array([[ 2,  6],
       [14, 18],
       [25, 29]])

In [27]:
a[ 2:21:2,:]

array([[13, 15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33, 35]])

In [28]:
a[ ::2,:]

array([[ 1,  3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33, 35]])

In [29]:
a[ ::-1,:]

array([[26, 28, 30, 32, 34, 36],
       [25, 27, 29, 31, 33, 35],
       [14, 16, 18, 20, 22, 24],
       [13, 15, 17, 19, 21, 23],
       [ 2,  4,  6,  8, 10, 12],
       [ 1,  3,  5,  7,  9, 11]])

In [30]:
a[np.r_[:len(a),0]]

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [13, 15, 17, 19, 21, 23],
       [14, 16, 18, 20, 22, 24],
       [25, 27, 29, 31, 33, 35],
       [26, 28, 30, 32, 34, 36],
       [ 1,  3,  5,  7,  9, 11]])

In [31]:
print(a)
a.T

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [13 15 17 19 21 23]
 [14 16 18 20 22 24]
 [25 27 29 31 33 35]
 [26 28 30 32 34 36]]


array([[ 1,  2, 13, 14, 25, 26],
       [ 3,  4, 15, 16, 27, 28],
       [ 5,  6, 17, 18, 29, 30],
       [ 7,  8, 19, 20, 31, 32],
       [ 9, 10, 21, 22, 33, 34],
       [11, 12, 23, 24, 35, 36]])

In [32]:
a.conj().T

array([[ 1,  2, 13, 14, 25, 26],
       [ 3,  4, 15, 16, 27, 28],
       [ 5,  6, 17, 18, 29, 30],
       [ 7,  8, 19, 20, 31, 32],
       [ 9, 10, 21, 22, 33, 34],
       [11, 12, 23, 24, 35, 36]])

In [33]:
a = np.random.rand(3,2)
b = np.random.rand(2,4)
print(a)
print(b)
a.dot(b)

[[0.7736453  0.19983054]
 [0.21091281 0.60955136]
 [0.36169537 0.19875326]]
[[0.89126044 0.53758875 0.31915806 0.0218805 ]
 [0.42665768 0.64682594 0.20327781 0.25434696]]


array([[0.77477868, 0.54515858, 0.28753625, 0.06775404],
       [0.44804801, 0.50765798, 0.19122279, 0.15965241],
       [0.40716438, 0.32300213, 0.15584012, 0.05846636]])

In [34]:
b = np.random.rand(3,2)
print(b)
a*b

[[0.4939727  0.94289964]
 [0.61516997 0.1295058 ]
 [0.30389977 0.86777493]]


array([[0.38215966, 0.18842014],
       [0.12974723, 0.07894044],
       [0.10991914, 0.1724731 ]])

In [35]:
a/b

array([[1.56617013, 0.21193193],
       [0.3428529 , 4.70674959],
       [1.1901798 , 0.2290378 ]])

In [36]:
a**3

array([[0.46304763, 0.00797968],
       [0.00938229, 0.22648055],
       [0.04731827, 0.00785132]])

In [37]:
(a>0.5)

array([[ True, False],
       [False,  True],
       [False, False]])

In [38]:
np.nonzero(a>.5)

(array([0, 1]), array([0, 1]))

In [39]:
v = np.random.rand(1,2)
print(a)
print(v)
a[:,np.nonzero(v>0.5)[0]]

[[0.7736453  0.19983054]
 [0.21091281 0.60955136]
 [0.36169537 0.19875326]]
[[0.5823321  0.63107908]]


array([[0.7736453 , 0.7736453 ],
       [0.21091281, 0.21091281],
       [0.36169537, 0.36169537]])

In [40]:
v = np.random.rand(2,1)

print(v.T)
#a[:,v.T>0.5]

[[0.46314629 0.29224545]]


In [41]:
a[a<0.5]=0
print(a)

[[0.7736453  0.        ]
 [0.         0.60955136]
 [0.         0.        ]]


In [42]:
a[:] = 3
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]]


In [43]:
y = a.copy()
print(y)

[[3. 3.]
 [3. 3.]
 [3. 3.]]


In [44]:
y = a[1,:].copy()
print(y)

[3. 3.]


In [46]:
y = a.flatten()
print(y)

[3. 3. 3. 3. 3. 3.]


In [47]:
np.arange(1.,11.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [49]:
np.arange(1.,11.)[:, np.newaxis]


array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [50]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [52]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
a = np.random.rand(4,4)
np.diag(a)

array([0.44613303, 0.46264602, 0.45576196, 0.64301418])

In [55]:
np.random.rand(3,4)

array([[0.0865568 , 0.77784488, 0.22774679, 0.32706333],
       [0.93336705, 0.02240891, 0.17269445, 0.48035555],
       [0.08941369, 0.33206716, 0.46774816, 0.05227694]])

In [56]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [57]:
np.mgrid[0:9.,0:6.] 

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [58]:
np.ogrid[0:9.,0:6.]

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]),
 array([[0., 1., 2., 3., 4., 5.]])]

In [59]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]),
 array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [60]:
np.ix_([1,2,4],[2,4,5])

(array([[1],
        [2],
        [4]]),
 array([[2, 4, 5]]))

In [61]:
np.tile(a, (2, 3))

array([[0.44613303, 0.03258362, 0.88631446, 0.75252111, 0.44613303,
        0.03258362, 0.88631446, 0.75252111, 0.44613303, 0.03258362,
        0.88631446, 0.75252111],
       [0.43553179, 0.46264602, 0.18816976, 0.23550007, 0.43553179,
        0.46264602, 0.18816976, 0.23550007, 0.43553179, 0.46264602,
        0.18816976, 0.23550007],
       [0.76370174, 0.48006877, 0.45576196, 0.82154256, 0.76370174,
        0.48006877, 0.45576196, 0.82154256, 0.76370174, 0.48006877,
        0.45576196, 0.82154256],
       [0.39579902, 0.43267459, 0.90476692, 0.64301418, 0.39579902,
        0.43267459, 0.90476692, 0.64301418, 0.39579902, 0.43267459,
        0.90476692, 0.64301418],
       [0.44613303, 0.03258362, 0.88631446, 0.75252111, 0.44613303,
        0.03258362, 0.88631446, 0.75252111, 0.44613303, 0.03258362,
        0.88631446, 0.75252111],
       [0.43553179, 0.46264602, 0.18816976, 0.23550007, 0.43553179,
        0.46264602, 0.18816976, 0.23550007, 0.43553179, 0.46264602,
        0.18816976,

In [62]:
a = np.random.rand(1,3)
b = np.random.rand(1,3)
np.hstack((a,b))

array([[0.55901741, 0.20648894, 0.23338941, 0.87587312, 0.79659048,
        0.02608219]])

In [63]:
np.concatenate((a,b))

array([[0.55901741, 0.20648894, 0.23338941],
       [0.87587312, 0.79659048, 0.02608219]])

In [64]:
a.max()

0.5590174056338614

In [65]:
a.max(0)

array([0.55901741, 0.20648894, 0.23338941])

In [66]:
a.max(1)

array([0.55901741])

In [67]:
np.maximum(a,b)

array([[0.87587312, 0.79659048, 0.23338941]])

In [69]:
v = np.random.rand(3,3)
np.sqrt(np.dot(v,v))

array([[1.35019689, 1.03043684, 1.05115842],
       [0.77712948, 0.65847363, 0.65662831],
       [0.93821834, 0.91630709, 0.92421403]])

In [70]:
np.logical_and(a,b)

array([[ True,  True,  True]])

In [75]:
np.logical_or(a,b)

array([[ True,  True,  True]])

In [77]:
a & b

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [78]:
a | b

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [79]:
a = np.random.rand(3,3)
print(a)
np.linalg.inv(a)

[[0.28160506 0.59950175 0.08278955]
 [0.22717512 0.98533334 0.61002845]
 [0.95571207 0.3834419  0.70943507]]


array([[ 1.4854054 , -1.25688112,  0.9074223 ],
       [ 1.34720557,  0.38533181, -0.48855479],
       [-2.72920668,  1.48493377,  0.45120118]])

In [80]:
np.linalg.pinv(a)

array([[ 1.4854054 , -1.25688112,  0.9074223 ],
       [ 1.34720557,  0.38533181, -0.48855479],
       [-2.72920668,  1.48493377,  0.45120118]])

In [81]:
np.linalg.matrix_rank(a)

3

In [82]:
b = np.random.rand(3,3)
np.linalg.solve(a,b)

array([[ 0.61739587,  0.10213303,  0.89621589],
       [ 0.72877163, -0.04751883,  0.69016441],
       [-0.31250949,  1.01969932, -0.34500996]])

In [83]:
U, S, Vh = np.linalg.svd(a)
V = Vh.T
print(V)
print(U)
print(S)

[[-0.52878055  0.6867368  -0.49878222]
 [-0.65759757 -0.70302068 -0.27079026]
 [-0.53661585  0.18480935  0.82334011]]
[[-0.34861162 -0.30297413 -0.88694792]
 [-0.64993639 -0.60369084  0.46167094]
 [-0.67531669  0.73740359  0.01353973]]
[1.68544113 0.70228204 0.26454189]


In [84]:
#np.linalg.cholesky(a).T

D,V = np.linalg.eig(a)
print(D)
print(V)

[1.6508543 +0.j        0.16275959+0.4039612j 0.16275959-0.4039612j]
[[-0.34275949+0.j         -0.29035634+0.4249725j  -0.29035634-0.4249725j ]
 [-0.69567287+0.j         -0.33095446-0.27989702j -0.33095446+0.27989702j]
 [-0.63131227+0.j          0.7397421 +0.j          0.7397421 -0.j        ]]


In [85]:
Q,R = scipy.linalg.qr(a)
#L,U = scipy.linalg.lu(a)
print(Q)
print(R)

[[-0.27556798 -0.41038176 -0.86928079]
 [-0.22230492 -0.85257424  0.47296689]
 [-0.9352234   0.32357993  0.14371228]]
[[-1.02190778 -0.74285177 -0.82190675]
 [ 0.         -0.96202031 -0.32451092]
 [ 0.          0.          0.31851043]]


In [86]:
np.fft.fft(a)

array([[ 0.96389636+0.j        , -0.05954059-0.4474859j ,
        -0.05954059+0.4474859j ],
       [ 1.82253691+0.j        , -0.57050577-0.32502357j,
        -0.57050577+0.32502357j],
       [ 2.04858904+0.j        ,  0.40927358+0.28231837j,
         0.40927358-0.28231837j]])

In [87]:
np.fft.ifft(a)

array([[ 0.32129879+0.j        , -0.01984686+0.14916197j,
        -0.01984686-0.14916197j],
       [ 0.6075123 +0.j        , -0.19016859+0.10834119j,
        -0.19016859-0.10834119j],
       [ 0.68286301+0.j        ,  0.13642453-0.09410612j,
         0.13642453+0.09410612j]])

In [88]:
a = np.random.randint(100, size=10)
print(a)
print(np.sort(a))

[70 56 11 56 22 55 39 86 98  0]
[ 0 11 22 39 55 56 56 70 86 98]


In [89]:
a.squeeze()

array([70, 56, 11, 56, 22, 55, 39, 86, 98,  0])