### Task 2


In [1]:
import numpy as np
import scipy.linalg
a = np.array([2, 4, 6])
b = np.array([8, 10, 12])
c = np.array([1, 3, 5])
d = np.array([7, 9, 11])
print(a)
print(b)
print(c)
print(d)

[2 4 6]
[ 8 10 12]
[1 3 5]
[ 7  9 11]


In [2]:
a.ndim

1

In [3]:
a.size

3

In [4]:
a.shape

(3,)

In [5]:
a.shape[1-1]

3

In [6]:
np.array([[1. ,2. ,3.], [4. ,5. ,6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
a = np.vstack([np.hstack([c,d]), np.hstack([a,b]), np.hstack([13, 15, 17, 19, 21, 23]), 
            np.hstack([14, 16, 18, 20, 22, 24]), np.hstack([25, 27, 29, 31, 33, 35]),
            np.hstack([26, 28, 30, 32, 34, 36])])

In [8]:
a[[-1]]

array([[26, 28, 30, 32, 34, 36]])

In [9]:
print(a)
a[1,4]

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [13 15 17 19 21 23]
 [14 16 18 20 22 24]
 [25 27 29 31 33 35]
 [26 28 30 32 34 36]]


10

In [10]:
a[1,:]

array([ 2,  4,  6,  8, 10, 12])

In [11]:
print(a)
a[0:5,:]

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [13 15 17 19 21 23]
 [14 16 18 20 22 24]
 [25 27 29 31 33 35]
 [26 28 30 32 34 36]]


array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [13, 15, 17, 19, 21, 23],
       [14, 16, 18, 20, 22, 24],
       [25, 27, 29, 31, 33, 35]])

In [12]:
a[-5:]

array([[ 2,  4,  6,  8, 10, 12],
       [13, 15, 17, 19, 21, 23],
       [14, 16, 18, 20, 22, 24],
       [25, 27, 29, 31, 33, 35],
       [26, 28, 30, 32, 34, 36]])

In [13]:
a[0:3][:,3:5]

array([[ 7,  9],
       [ 8, 10],
       [19, 21]])

In [14]:
a[np.ix_([1,3,4],[0,2])]

array([[ 2,  6],
       [14, 18],
       [25, 29]])

In [15]:
a[ 2:21:2,:]

array([[13, 15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33, 35]])

In [16]:
a[ ::2,:]

array([[ 1,  3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33, 35]])

In [17]:
a[ ::-1,:]

array([[26, 28, 30, 32, 34, 36],
       [25, 27, 29, 31, 33, 35],
       [14, 16, 18, 20, 22, 24],
       [13, 15, 17, 19, 21, 23],
       [ 2,  4,  6,  8, 10, 12],
       [ 1,  3,  5,  7,  9, 11]])

In [18]:
a[np.r_[:len(a),0]]

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12],
       [13, 15, 17, 19, 21, 23],
       [14, 16, 18, 20, 22, 24],
       [25, 27, 29, 31, 33, 35],
       [26, 28, 30, 32, 34, 36],
       [ 1,  3,  5,  7,  9, 11]])

In [19]:
print(a)
a.T

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]
 [13 15 17 19 21 23]
 [14 16 18 20 22 24]
 [25 27 29 31 33 35]
 [26 28 30 32 34 36]]


array([[ 1,  2, 13, 14, 25, 26],
       [ 3,  4, 15, 16, 27, 28],
       [ 5,  6, 17, 18, 29, 30],
       [ 7,  8, 19, 20, 31, 32],
       [ 9, 10, 21, 22, 33, 34],
       [11, 12, 23, 24, 35, 36]])

In [20]:
a.conj().T

array([[ 1,  2, 13, 14, 25, 26],
       [ 3,  4, 15, 16, 27, 28],
       [ 5,  6, 17, 18, 29, 30],
       [ 7,  8, 19, 20, 31, 32],
       [ 9, 10, 21, 22, 33, 34],
       [11, 12, 23, 24, 35, 36]])

In [21]:
a = np.random.rand(3,2)
b = np.random.rand(2,4)
print(a)
print(b)
a.dot(b)

[[0.7248529  0.74793713]
 [0.83444054 0.35011028]
 [0.63903264 0.86002835]]
[[0.17594623 0.80758594 0.54836267 0.86003848]
 [0.1165602  0.82481196 0.71841097 0.0598166 ]]


array([[0.21471483, 1.20228849, 0.93480851, 0.66814044],
       [0.18762559, 0.96265759, 0.70909911, 0.73859338],
       [0.21268046, 1.22543544, 0.96827545, 0.60103663]])

In [22]:
b = np.random.rand(3,2)
print(b)
a*b

[[0.07408974 0.34346414]
 [0.02707776 0.59092675]
 [0.40750159 0.99911816]]


array([[0.05370416, 0.25688958],
       [0.02259478, 0.20688953],
       [0.26040682, 0.85926994]])

In [23]:
a/b

array([[ 9.78344476,  2.177628  ],
       [30.81645613,  0.59247662],
       [ 1.56817214,  0.86078743]])

In [24]:
a**3

array([[0.38084621, 0.41840347],
       [0.58101344, 0.04291554],
       [0.2609571 , 0.6361189 ]])

In [25]:
(a>0.5)

array([[ True,  True],
       [ True, False],
       [ True,  True]])

In [26]:
np.nonzero(a>.5)

(array([0, 0, 1, 2, 2]), array([0, 1, 0, 0, 1]))

In [27]:
v = np.random.rand(1,2)
print(a)
print(v)
a[:,np.nonzero(v>0.5)[0]]

[[0.7248529  0.74793713]
 [0.83444054 0.35011028]
 [0.63903264 0.86002835]]
[[0.91322612 0.15321591]]


array([[0.7248529 ],
       [0.83444054],
       [0.63903264]])

In [28]:
v = np.random.rand(2,1)

print(v.T)
#a[:,v.T>0.5]

[[0.32336719 0.31525312]]


In [29]:
a[a<0.5]=0
print(a)

[[0.7248529  0.74793713]
 [0.83444054 0.        ]
 [0.63903264 0.86002835]]


In [30]:
a[:] = 3
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]]


In [31]:
y = a.copy()
print(y)

[[3. 3.]
 [3. 3.]
 [3. 3.]]


In [32]:
y = a[1,:].copy()
print(y)

[3. 3.]


In [33]:
y = a.flatten()
print(y)

[3. 3. 3. 3. 3. 3.]


In [34]:
np.arange(1.,11.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
np.arange(1.,11.)[:, np.newaxis]


array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [37]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [39]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
a = np.random.rand(4,4)
np.diag(a)

array([0.14586076, 0.23740469, 0.90950199, 0.66425218])

In [42]:
np.random.rand(3,4)

array([[0.03974142, 0.58246311, 0.74540325, 0.55305489],
       [0.30443921, 0.11889547, 0.6567559 , 0.17413868],
       [0.08123134, 0.99826424, 0.20739253, 0.36184461]])

In [43]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [44]:
np.mgrid[0:9.,0:6.] 

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [45]:
np.ogrid[0:9.,0:6.]

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]),
 array([[0., 1., 2., 3., 4., 5.]])]

In [46]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]),
 array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [47]:
np.ix_([1,2,4],[2,4,5])

(array([[1],
        [2],
        [4]]),
 array([[2, 4, 5]]))

In [48]:
np.tile(a, (2, 3))

array([[0.14586076, 0.42733253, 0.26204548, 0.68810027, 0.14586076,
        0.42733253, 0.26204548, 0.68810027, 0.14586076, 0.42733253,
        0.26204548, 0.68810027],
       [0.56611087, 0.23740469, 0.85573562, 0.72852548, 0.56611087,
        0.23740469, 0.85573562, 0.72852548, 0.56611087, 0.23740469,
        0.85573562, 0.72852548],
       [0.35923194, 0.64467463, 0.90950199, 0.21285238, 0.35923194,
        0.64467463, 0.90950199, 0.21285238, 0.35923194, 0.64467463,
        0.90950199, 0.21285238],
       [0.28975286, 0.78757713, 0.28390964, 0.66425218, 0.28975286,
        0.78757713, 0.28390964, 0.66425218, 0.28975286, 0.78757713,
        0.28390964, 0.66425218],
       [0.14586076, 0.42733253, 0.26204548, 0.68810027, 0.14586076,
        0.42733253, 0.26204548, 0.68810027, 0.14586076, 0.42733253,
        0.26204548, 0.68810027],
       [0.56611087, 0.23740469, 0.85573562, 0.72852548, 0.56611087,
        0.23740469, 0.85573562, 0.72852548, 0.56611087, 0.23740469,
        0.85573562,

In [49]:
a = np.random.rand(1,3)
b = np.random.rand(1,3)
np.hstack((a,b))

array([[0.84870541, 0.15701011, 0.25301356, 0.12569958, 0.05335507,
        0.69456855]])

In [50]:
np.concatenate((a,b))

array([[0.84870541, 0.15701011, 0.25301356],
       [0.12569958, 0.05335507, 0.69456855]])

In [51]:
a.max()

0.8487054079675388

In [52]:
a.max(0)

array([0.84870541, 0.15701011, 0.25301356])

In [53]:
a.max(1)

array([0.84870541])

In [54]:
np.maximum(a,b)

array([[0.84870541, 0.15701011, 0.69456855]])

In [55]:
v = np.random.rand(3,3)
np.sqrt(np.dot(v,v))

array([[1.21407377, 1.14318693, 0.79901211],
       [1.097392  , 1.17047624, 0.79286826],
       [1.08150377, 1.09030319, 0.85210234]])

In [56]:
np.logical_and(a,b)

array([[ True,  True,  True]])

In [57]:
np.logical_or(a,b)

array([[ True,  True,  True]])

In [58]:
a & b

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [59]:
a | b

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [60]:
a = np.random.rand(3,3)
print(a)
np.linalg.inv(a)

[[0.1450725  0.3369178  0.10744926]
 [0.69409358 0.02795979 0.76247322]
 [0.35785321 0.34134457 0.21790723]]


array([[-8.9246889 , -1.29002272,  8.91461456],
       [ 4.26988368, -0.24012499, -1.26524925],
       [ 7.96773453,  2.49465854, -8.06874323]])

In [61]:
np.linalg.pinv(a)

array([[-8.9246889 , -1.29002272,  8.91461456],
       [ 4.26988368, -0.24012499, -1.26524925],
       [ 7.96773453,  2.49465854, -8.06874323]])

In [62]:
np.linalg.matrix_rank(a)

3

In [63]:
b = np.random.rand(3,3)
np.linalg.solve(a,b)

array([[ 4.64957819, -2.99678138,  2.01840183],
       [ 0.06509741,  1.98081934,  0.04599202],
       [-4.04192524,  3.8717173 , -0.78387552]])

In [64]:
U, S, Vh = np.linalg.svd(a)
V = Vh.T
print(V)
print(U)
print(S)

[[-0.69387941  0.0160468   0.7199124 ]
 [-0.20735625  0.95295253 -0.22109922]
 [-0.68959028 -0.30269454 -0.65790673]]
[[-0.21399387  0.66360826 -0.71681985]
 [-0.88635357 -0.44035357 -0.1430597 ]
 [-0.41058977  0.60474194  0.68242452]]
[1.14312056 0.43831629 0.05684044]


In [65]:
#np.linalg.cholesky(a).T

D,V = np.linalg.eig(a)
print(D)
print(V)

[ 0.94327283 -0.06151468 -0.49081863]
[[-0.38766829 -0.73106404  0.43080787]
 [-0.74555021  0.24520096 -0.87869234]
 [-0.5420961   0.63672746  0.20568021]]


In [66]:
Q,R = scipy.linalg.qr(a)
#L,U = scipy.linalg.lu(a)
print(Q)
print(R)

[[-0.18264798  0.70408007 -0.68622953]
 [-0.87387195 -0.43610218 -0.21485509]
 [-0.45054138  0.56043388  0.69492901]]
[[-0.79427379 -0.23976049 -0.78410557]
 [ 0.          0.41632485 -0.13474076]
 [ 0.          0.         -0.08612605]]


In [67]:
np.fft.fft(a)

array([[ 0.58943956+0.j        , -0.07711102-0.19872559j,
        -0.07711102+0.19872559j],
       [ 1.48452659+0.j        ,  0.29887707+0.63610729j,
         0.29887707-0.63610729j],
       [ 0.91710501+0.j        ,  0.07822731-0.10689988j,
         0.07822731+0.10689988j]])

In [68]:
np.fft.ifft(a)

array([[ 0.19647985+0.j        , -0.02570367+0.06624186j,
        -0.02570367-0.06624186j],
       [ 0.4948422 +0.j        ,  0.09962569-0.21203576j,
         0.09962569+0.21203576j],
       [ 0.30570167+0.j        ,  0.02607577+0.03563329j,
         0.02607577-0.03563329j]])

In [69]:
a = np.random.randint(100, size=10)
print(a)
print(np.sort(a))

[50 91  4 83  6 19 55 16 85 69]
[ 4  6 16 19 50 55 69 83 85 91]


In [70]:
a.squeeze()

array([50, 91,  4, 83,  6, 19, 55, 16, 85, 69])